"""Build the daily GBP artwork template and planner sheet from one JSON source.

    python3 design/build-gbp-daily.py

strategy/gbp-daily-content.json is the only file to hand edit. This script
regenerates design/gbp-daily.html from it and rewrites the GBP Daily tab in
strategy/ig-content-strategy.xlsx, keeping whatever Status and Notes are
already typed into that tab. Render the artwork afterwards with

    python3 design/render.py gbp-daily
"""
import json
import os
import datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTENT = os.path.join(ROOT, 'strategy', 'gbp-daily-content.json')
TEMPLATE = os.path.join(ROOT, 'design', 'gbp-daily.html')
SHEET = os.path.join(ROOT, 'strategy', 'ig-content-strategy.xlsx')
TAB = 'GBP Daily'
IMG_DIR = 'content/gbp'


def load():
    with open(CONTENT, encoding='utf-8') as f:
        return json.load(f)


def image_path(post):
    """Flat, date-named so the folder reads in posting order."""
    return f"{IMG_DIR}/{post['date']}-{post['slug']}.jpg"


# --- artwork template ------------------------------------------------------

def build_html(data):
    """Same brand and 1200x900 safe-area rules as gbp.html, keyed by date."""
    css = open(os.path.join(ROOT, 'design', 'gbp.html'), encoding='utf-8').read()
    css = css[css.index('<style>'):css.index('</style>') + len('</style>')]
    posts = {p['date']: {k: p[k] for k in ('label', 'serif', 'script', 'body', 'button')}
             for p in data['posts']}
    first = data['posts'][0]['date']
    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Google Business Profile — daily 1200x900</title>
<!-- Generated by design/build-gbp-daily.py. Edit strategy/gbp-daily-content.json,
     not this file. Preview a day with ?date=2026-09-14 -->
{css}
</head>
<body>
<div id="stage"></div>

<script>
const POSTS = {json.dumps(posts, indent=2, ensure_ascii=False)};

const P = POSTS[new URLSearchParams(location.search).get('date') || '{first}'];

document.getElementById('stage').innerHTML = `
<div class="slide">
  <img class="monogram" src="brand/logo-monogram.png" width="76" alt="LB">
  <div class="safe">
    <div class="label">${{P.label}}</div>
    <div style="margin-top:18px">
      <div class="serif">${{P.serif}}</div>
      <div class="script">${{P.script}}</div>
    </div>
    <div class="body">${{P.body}}</div>
    <div class="button">${{P.button}}</div>
  </div>
  <div class="handle">@luxury_beauty_aestheticz</div>
</div>`;
</script>
</body>
</html>
"""


# --- planner tab -----------------------------------------------------------

HEADERS = ['Date', 'Day', 'Source', 'Pillar', 'Post Text (first 80 chars show)',
           'Chars', 'CTA Button', 'CTA Link', 'Image File', 'Image', 'Preview',
           'Status', 'Notes']


def build_sheet(data):
    import openpyxl
    from openpyxl.styles import Font, Alignment, PatternFill
    from openpyxl.utils import get_column_letter

    meta = data['_meta']
    wb = openpyxl.load_workbook(SHEET)

    # keep anything already typed into Status / Notes before the tab is replaced
    kept = {}
    if TAB in wb.sheetnames:
        old = wb[TAB]
        head = [c.value for c in old[1]]
        if 'Date' in head:
            di = head.index('Date')
            si = head.index('Status') if 'Status' in head else None
            ni = head.index('Notes') if 'Notes' in head else None
            for row in old.iter_rows(min_row=2, values_only=True):
                key = row[di]
                key = key.strftime('%Y-%m-%d') if hasattr(key, 'strftime') else str(key)
                kept[key] = (row[si] if si is not None else None,
                             row[ni] if ni is not None else None)
        del wb[TAB]

    ws = wb.create_sheet(TAB, wb.sheetnames.index('Posting Schedule') + 1)

    ink = Font(name='Calibri', size=11)
    ws.append(HEADERS)
    for c in ws[1]:
        c.font = Font(bold=True, color='FFFFFF')
        c.fill = PatternFill('solid', fgColor='2E2A23')
        c.alignment = Alignment(vertical='center')
    ws.freeze_panes = 'C2'

    base = f"https://github.com/RepoKing23/InstagramCarousel/blob/{meta['branch']}/"
    raw = f"https://raw.githubusercontent.com/RepoKing23/InstagramCarousel/{meta['branch']}/"

    for p in data['posts']:
        img = image_path(p)
        status, notes = kept.get(p['date'], (None, None))
        ws.append([
            datetime.datetime.strptime(p['date'], '%Y-%m-%d'),
            p['day'], p['source'], p['pillar'], p['text'], len(p['text']),
            meta['cta_button'], meta['instagram_url'], img.split('/')[-1],
            'Open image', f'=IMAGE("{raw}{img}")', status or 'Ready', notes or '',
        ])
        r = ws.max_row
        ws.cell(r, 1).number_format = 'yyyy-mm-dd'
        link = ws.cell(r, HEADERS.index('CTA Link') + 1)
        link.hyperlink = meta['instagram_url']
        link.value = meta['instagram']
        link.style = 'Hyperlink'
        im = ws.cell(r, HEADERS.index('Image') + 1)
        im.hyperlink = f'{base}{img}?raw=1'
        im.style = 'Hyperlink'
        for col in ('Post Text (first 80 chars show)', 'Notes'):
            ws.cell(r, HEADERS.index(col) + 1).alignment = Alignment(wrap_text=True, vertical='top')
        # Sunday and Wednesday have no Instagram post behind them
        if p['source'] == 'GBP only':
            for c in ws[r]:
                c.fill = PatternFill('solid', fgColor='F3EEE5')
        for c in ws[r]:
            if not c.font.bold:
                c.font = ink

    widths = {'A': 12, 'B': 6, 'C': 34, 'D': 18, 'E': 78, 'F': 7, 'G': 12,
              'H': 26, 'I': 34, 'J': 12, 'K': 14, 'L': 10, 'M': 30}
    for col, w in widths.items():
        ws.column_dimensions[col].width = w
    for r in range(2, ws.max_row + 1):
        ws.row_dimensions[r].height = 58

    wb.save(SHEET)
    return ws.max_row - 1


def main():
    data = load()
    with open(TEMPLATE, 'w', encoding='utf-8') as f:
        f.write(build_html(data))
    print(f'wrote {os.path.relpath(TEMPLATE, ROOT)}  ({len(data["posts"])} days)')
    n = build_sheet(data)
    print(f'wrote "{TAB}" tab in {os.path.relpath(SHEET, ROOT)}  ({n} rows)')


if __name__ == '__main__':
    main()
