/* Generated by design/build-octnov.py from strategy/plan-*.json.
   Edit the plan, not this file. */
window.OCTNOV = {
 "carousels": {
  "botox-in-oakville-first-appointment": {
   "label": "Botox In Oakville &#183; First Timers",
   "coverSerif": "YOUR FIRST",
   "coverScript": "Botox appointment.",
   "coverSub": "What actually happens, start to finish, at the Oakville studio.",
   "points": [
    {
     "h": "It starts with a real consult",
     "b": "We talk first. What bothers you, your health history, anything you have had before. Nothing is opened until you know the plan and the price."
    },
    {
     "h": "I watch your face move",
     "b": "Frown, lift, squint, smile. Where your muscles pull decides where the units go, so the plan is built for your face and nobody else's."
    },
    {
     "h": "The treatment takes minutes",
     "b": "Around ten minutes for most areas. A few small pinches, numbing if you want it, and you are back to your day straight after."
    },
    {
     "h": "Results arrive slowly, on purpose",
     "b": "You will start to notice a change around day three to five. The full result settles at two weeks. Nothing looks different when you walk out."
    },
    {
     "h": "We check in at two weeks",
     "b": "That visit is where we adjust if anything needs it. Nobody leaves with almost right."
    }
   ],
   "ctaSerif": "READY FOR",
   "ctaScript": "your first?",
   "ctaBody": "Book a consult at the Oakville studio. Bring every question, even the one you think is silly.",
   "button": "DM the word FIRST"
  },
  "dermal-fillers-wont-make-you-look-fake": {
   "label": "Dermal Fillers &#183; The Honest Version",
   "coverSerif": "FILLER IS NOT",
   "coverScript": "the problem.",
   "coverSub": "Overdone faces come from technique, not the product. Here is what to watch for.",
   "points": [
    {
     "h": "Too much, too soon",
     "b": "Most overdone results are several syringes in one sitting. Natural work is often half a syringe, reviewed at two weeks, then built slowly if needed."
    },
    {
     "h": "Chasing lines instead of shape",
     "b": "Filling every crease flattens a face. Supporting the cheek or the chin often softens a line better than putting filler in the line itself."
    },
    {
     "h": "Ignoring your proportions",
     "b": "Lips, cheeks and jaw have to agree with each other. A result that ignores your natural ratios is the one people notice."
    },
    {
     "h": "The wrong product for the area",
     "b": "Fillers differ in how firm and how mobile they are. Lips need softness, a jawline needs structure. One product for everything is a shortcut."
    },
    {
     "h": "A provider who never says stop",
     "b": "The best result often comes from the syringe we did not open. You want an injector who is comfortable telling you that."
    }
   ],
   "ctaSerif": "NATURAL IS",
   "ctaScript": "a decision.",
   "ctaBody": "Book a dermal filler consult in Oakville and we will plan the version nobody can spot.",
   "button": "DM the word FILLER"
  },
  "botox-treatment-step-by-step": {
   "label": "Botox Treatment &#183; How It Works",
   "coverSerif": "WHAT BOTOX",
   "coverScript": "actually treats.",
   "coverSub": "The areas it is brilliant for, and the ones where it is the wrong tool.",
   "points": [
    {
     "h": "How it works",
     "b": "It relaxes the specific muscle that folds the skin. Less folding means the line softens and, over time, stops deepening."
    },
    {
     "h": "Frown lines",
     "b": "The two vertical lines between the brows. The most requested area, and usually the one that makes people look tired or cross when they are neither."
    },
    {
     "h": "Forehead lines",
     "b": "Treated lightly so your brows still lift. Too much here is what causes the heavy, frozen look people are afraid of."
    },
    {
     "h": "Crow's feet",
     "b": "The lines at the corners of the eyes when you smile. Softened, not erased, so your smile still reaches your eyes."
    },
    {
     "h": "What it cannot do",
     "b": "It does not add volume or lift sagging skin. Lines from lost volume need a different treatment, and I will tell you if that is you."
    }
   ],
   "ctaSerif": "NOT SURE",
   "ctaScript": "which you need?",
   "ctaBody": "Book a Botox consult in Oakville. We will look at your face together and plan only what it needs.",
   "button": "DM the word BOTOX"
  },
  "electrolysis-vs-laser-hair-removal": {
   "label": "Electrolysis vs Laser &#183; Honestly",
   "coverSerif": "ELECTROLYSIS",
   "coverScript": "or laser?",
   "coverSub": "Both remove hair. Only one is recognised as permanent. Here is how to choose.",
   "points": [
    {
     "h": "How each one works",
     "b": "Laser heats pigment in the hair to damage the follicle. Electrolysis treats each follicle directly with a fine probe and a small current."
    },
    {
     "h": "Hair colour matters for laser",
     "b": "Laser needs dark hair to target. Grey, white, blonde and red hairs do not absorb it. Electrolysis does not depend on colour at all."
    },
    {
     "h": "Skin tone matters too",
     "b": "Laser works best with contrast between skin and hair. Electrolysis suits every skin tone because it never targets pigment."
    },
    {
     "h": "Reduction or removal",
     "b": "Laser is recognised as permanent reduction. Electrolysis is recognised as permanent removal, follicle by follicle."
    },
    {
     "h": "Area and time",
     "b": "Laser is faster for large areas like legs. Electrolysis shines on the face, brows and stubborn stray hairs laser left behind."
    }
   ],
   "ctaSerif": "STILL",
   "ctaScript": "deciding?",
   "ctaBody": "Book an electrolysis consult in Oakville. We will look at your hair and skin and tell you honestly which suits you.",
   "button": "DM the word HAIR"
  },
  "lip-filler-aftercare-your-first-week": {
   "label": "Lip Filler Aftercare &#183; Week One",
   "coverSerif": "",
   "coverScript": "",
   "coverSub": "",
   "points": [
    {
     "h": "Day zero: swollen is normal",
     "b": "Your lips will look bigger today than they will in two weeks. Ice on and off, ten minutes at a time. Do not judge the result yet."
    },
    {
     "h": "First 48 hours: keep it cool",
     "b": "No gym, sauna, hot yoga or long hot showers. Heat and blood flow both make swelling worse. Sleep propped up on an extra pillow."
    },
    {
     "h": "Hands off",
     "b": "No pressing, pinching or massaging unless I asked you to. Hold off on dental work and, if you can, flying for a few days."
    },
    {
     "h": "Drink more water",
     "b": "Hyaluronic acid draws water. Hydrated lips feel softer and settle more evenly. Lip balm helps too."
    },
    {
     "h": "Day 14: the real result",
     "b": "Small lumps early on usually settle on their own. We review at two weeks, and you can message me any time before then."
    }
   ],
   "ctaSerif": "SAVE",
   "ctaScript": "this one.",
   "ctaBody": "Every lip filler client at the Oakville studio leaves with this in writing and my number.",
   "button": "DM the word LIPS"
  },
  "botox-for-men-oakville": {
   "label": "Botox For Men &#183; Oakville",
   "coverSerif": "BOTOX",
   "coverScript": "for men.",
   "coverSub": "Not a trend. Just the appointment he keeps putting off.",
   "points": [
    {
     "h": "Men usually need more units",
     "b": "Male facial muscles tend to be stronger and larger, so the dose is different. A template dose is how men end up underwhelmed."
    },
    {
     "h": "The brows stay masculine",
     "b": "A lower, flatter brow is kept on purpose. Arching a man's brows is the fastest way to make treatment obvious."
    },
    {
     "h": "The goal is less tired",
     "b": "Most men want to stop looking stressed or angry in photos. Softening the frown line does most of that work."
    },
    {
     "h": "Nobody needs to know",
     "b": "Ten minutes, no downtime, back to work straight after. Results build over two weeks, so there is no reveal day."
    },
    {
     "h": "Questions are welcome",
     "b": "First timers often come in with a partner's list. Bring it. The consult is where we talk it through."
    }
   ],
   "ctaSerif": "BOOK",
   "ctaScript": "the ten minutes.",
   "ctaBody": "Botox for men at the Oakville studio. Private, one client at a time, nurse practitioner led.",
   "button": "DM the word BOTOX"
  },
  "facial-balancing-dermal-fillers": {
   "label": "Facial Balancing &#183; Faces, Not Lines",
   "coverSerif": "FACES,",
   "coverScript": "not lines.",
   "coverSub": "Why the best dermal filler plan often starts somewhere you did not point to.",
   "points": [
    {
     "h": "It is about proportion",
     "b": "Facial balancing looks at how your chin, lips, cheeks and jaw relate. Small changes to one feature change how the others read."
    },
    {
     "h": "The chin changes the lips",
     "b": "A soft chin can make lips look too full or a nose look larger. Supporting the chin is sometimes the whole answer."
    },
    {
     "h": "Cheeks lift the lower face",
     "b": "Restoring a little cheek support can soften the lines around the mouth without putting filler in those lines."
    },
    {
     "h": "Less, placed well",
     "b": "Balancing is rarely about lots of product. It is about the right amount in two or three places that matter."
    },
    {
     "h": "Planned over time",
     "b": "We often stage it across visits, reviewing at two weeks, so every step is a decision and never a guess."
    }
   ],
   "ctaSerif": "LET'S LOOK",
   "ctaScript": "at the whole face.",
   "ctaBody": "Book a facial balancing consult in Oakville. You leave with a plan, whether or not we treat that day.",
   "button": "DM the word BALANCE"
  },
  "botox-before-the-holidays-timeline": {
   "label": "Rested By The Holidays &#183; Timeline",
   "coverSerif": "BOTOX BY",
   "coverScript": "the holidays.",
   "coverSub": "Work backwards from your party. Here is when to book.",
   "points": [
    {
     "h": "Results take two weeks",
     "b": "Botox starts working around day three to five and settles at two weeks. Booking the week of your event is too late."
    },
    {
     "h": "Leave room for the review",
     "b": "Your two week check in is when small adjustments happen. Book three to four weeks ahead so that visit lands before the party."
    },
    {
     "h": "First time? Go earlier",
     "b": "If you have never had Botox, give yourself four to six weeks. You want to know how your face responds before the photos."
    },
    {
     "h": "Filler needs longer",
     "b": "Swelling can take up to two weeks to settle. Book filler at least four weeks before anything with a camera."
    },
    {
     "h": "December fills fast",
     "b": "Late November and early December are the busiest weeks of the year at the studio. The calm slots go first."
    }
   ],
   "ctaSerif": "PICK",
   "ctaScript": "your date.",
   "ctaBody": "Tell me your event date and I will tell you the latest day to book at the Oakville studio.",
   "button": "DM your event date"
  },
  "party-season-prep-plan": {
   "label": "Party Season Prep &#183; The Order",
   "coverSerif": "PLANNED",
   "coverScript": "backwards.",
   "coverSub": "What to book, in what order, so you are ready before the first invitation.",
   "points": [
    {
     "h": "Eight weeks out: electrolysis",
     "b": "It is a course, not a single visit. Starting now means fewer stray hairs by December, not a red chin the night before."
    },
    {
     "h": "Four to six weeks: filler",
     "b": "Swelling needs up to two weeks to settle, and your review needs a slot after that. Filler goes early."
    },
    {
     "h": "Three to four weeks: Botox",
     "b": "Settles at two weeks, with your check in straight after. Right in time for the first party."
    },
    {
     "h": "The final week: nothing new",
     "b": "No first time treatments the week of an event. This is the week for sleep, water and your usual skincare."
    },
    {
     "h": "Book the review too",
     "b": "The appointment that makes everything work is the one after. Put it in the calendar when you book."
    }
   ],
   "ctaSerif": "YOUR",
   "ctaScript": "holiday plan.",
   "ctaBody": "Send your event date and I will map out your plan at the Oakville studio.",
   "button": "DM the word PARTY"
  },
  "under-eye-filler-honest-truth": {
   "label": "Under Eye Filler &#183; Honestly",
   "coverSerif": "UNDER EYE",
   "coverScript": "filler.",
   "coverSub": "Brilliant for some. The wrong answer for many. Here is how to tell.",
   "points": [
    {
     "h": "It treats hollows",
     "b": "If the tiredness comes from a groove or shadow under the eye, careful filler can soften it beautifully."
    },
    {
     "h": "It does not fix puffiness",
     "b": "Puffy bags are often fat or fluid. Adding filler can make them look bigger. That is a no from me."
    },
    {
     "h": "It does not fix pigment",
     "b": "Brown or purple darkness in the skin itself is colour, not volume. Filler will not change it."
    },
    {
     "h": "Less is everything here",
     "b": "The under eye is thin and unforgiving. Tiny amounts, placed deep and slowly, reviewed at two weeks."
    },
    {
     "h": "Sometimes the cheek is the answer",
     "b": "Supporting the mid cheek can lift the shadow without touching the under eye at all."
    }
   ],
   "ctaSerif": "NOT SURE",
   "ctaScript": "which is you?",
   "ctaBody": "Book an under eye assessment in Oakville. If filler is not right for you, I will say so.",
   "button": "DM the word EYES"
  },
  "electrolysis-for-hormonal-facial-hair": {
   "label": "Facial Electrolysis &#183; Hormonal Hair",
   "coverSerif": "HORMONAL",
   "coverScript": "facial hair.",
   "coverSub": "Common, rarely talked about, and very treatable. Here is what to know.",
   "points": [
    {
     "h": "It is more common than you think",
     "b": "Coarse hair on the chin, jaw and neck is one of the most common things people quietly deal with, often linked to PCOS or hormone changes."
    },
    {
     "h": "Electrolysis treats every hair type",
     "b": "Dark coarse hairs and fine light ones alike. Laser often misses the light and grey hairs that come later."
    },
    {
     "h": "Hormones can create new hairs",
     "b": "Treated follicles stop, but hormones can wake up new ones. That is why care from your doctor matters alongside treatment."
    },
    {
     "h": "Stop tweezing now",
     "b": "Tweezing can make hairs deeper and more stubborn. Trim or shave until your first session so we can treat them properly."
    },
    {
     "h": "Private and judgement free",
     "b": "One client at a time, in a private room. Nobody here will be surprised by anything, and you will never be rushed."
    }
   ],
   "ctaSerif": "YOU ARE",
   "ctaScript": "not alone.",
   "ctaBody": "Book a private facial electrolysis consult in Oakville. Ask anything. Nothing is awkward here.",
   "button": "DM the word HAIR"
  },
  "choosing-a-luxury-med-spa-oakville": {
   "label": "Choosing A Med Spa &#183; Oakville",
   "coverSerif": "WHAT LUXURY",
   "coverScript": "really means.",
   "coverSub": "Five questions to ask any Oakville med spa before you book.",
   "points": [
    {
     "h": "Who is injecting me?",
     "b": "You should know their name and credentials before you book, and see the same person at your follow up."
    },
    {
     "h": "How long is my appointment?",
     "b": "A first visit that allows time for a real consult is a good sign. Ten minutes door to door is not."
    },
    {
     "h": "Will you ever say no?",
     "b": "A clinic that never turns anyone away is selling. You want someone comfortable saying not yet."
    },
    {
     "h": "What happens if I am unhappy?",
     "b": "Ask about the review appointment, and what the plan is if something needs adjusting or goes wrong."
    },
    {
     "h": "Is it private?",
     "b": "Luxury is a room that is yours for the whole appointment, not a curtain and a queue."
    }
   ],
   "ctaSerif": "ASK US",
   "ctaScript": "all five.",
   "ctaBody": "Book a consult at the Oakville studio and ask every one. We will be glad you did.",
   "button": "DM to book"
  },
  "skincare-botox-filler-right-order": {
   "label": "The Right Order &#183; Skin, Botox, Filler",
   "coverSerif": "WHAT COMES",
   "coverScript": "first?",
   "coverSub": "Skin, then movement, then volume. Here is why the order saves you money.",
   "points": [
    {
     "h": "Start with skin",
     "b": "Daily sunscreen and a simple routine do more for texture and tone than any injectable. Nothing replaces that foundation."
    },
    {
     "h": "Then movement: Botox",
     "b": "Relaxing the muscles that fold your skin softens expression lines and stops new ones deepening."
    },
    {
     "h": "Then volume: filler",
     "b": "Once movement is managed, you can see what volume is actually missing. Often it is less than you thought."
    },
    {
     "h": "Why the order matters",
     "b": "Filler put into a line that Botox would have softened is product you did not need. The order saves money."
    },
    {
     "h": "Your plan may differ",
     "b": "Some faces need volume first. That is what the consult is for, and why nobody gets a template."
    }
   ],
   "ctaSerif": "BUILD",
   "ctaScript": "your order.",
   "ctaBody": "Book a consult in Oakville and leave with a plan in the right order for your face.",
   "button": "DM the word PLAN"
  },
  "gift-of-glow-holiday-gift-certificates": {
   "label": "The Gift Of Glow &#183; Holiday",
   "coverSerif": "THE GIFT",
   "coverScript": "of glow.",
   "coverSub": "Holiday gift certificates for the Oakville studio. Here is how they work.",
   "points": [
    {
     "h": "Any amount",
     "b": "Choose a value that suits you. It can cover a full treatment or go toward one."
    },
    {
     "h": "Any treatment",
     "b": "Botox, dermal filler or electrolysis. They pick, after a consult, not before."
    },
    {
     "h": "Always starts with a consult",
     "b": "Nobody is locked into a treatment they did not want. The consult decides what suits them."
    },
    {
     "h": "Ready fast",
     "b": "Order through a DM and it can be sent by email or ready to pick up at the studio in time for the holidays."
    },
    {
     "h": "Dropping a hint?",
     "b": "Send this carousel to the person who never knows what to get you. We will not tell."
    }
   ],
   "ctaSerif": "GIVE",
   "ctaScript": "the glow.",
   "ctaBody": "Order a gift certificate for the Oakville studio. DM the word GIFT and it is done.",
   "button": "DM the word GIFT"
  },
  "december-botox-last-call": {
   "label": "Last Call &#183; December Plan",
   "coverSerif": "LAST CALL",
   "coverScript": "for December.",
   "coverSub": "Book this week and you are settled, and reviewed, before the parties.",
   "points": [
    {
     "h": "This week: book",
     "b": "Botox booked this week settles at two weeks, which lands in mid December with time for your review."
    },
    {
     "h": "Week two: it settles",
     "b": "You will notice it softening from day three to five. Do not judge it before day fourteen."
    },
    {
     "h": "Week three: review",
     "b": "Your check in is where anything small gets adjusted, ahead of the busiest party weekends."
    },
    {
     "h": "Missed it? New Year's",
     "b": "Booking after the first week of December? We plan for New Year's Eve instead. There is still time for that."
    },
    {
     "h": "Filler this late?",
     "b": "Only if we have treated you before and know how you swell. First time filler waits for January."
    }
   ],
   "ctaSerif": "BOOK",
   "ctaScript": "this week.",
   "ctaBody": "Botox at the Oakville studio, one client at a time. The calm December slots go first.",
   "button": "DM the word DECEMBER"
  }
 },
 "singles": {
  "what-is-electrolysis": {
   "label": "Electrolysis &#183; Oakville",
   "serif": "WHAT IS",
   "script": "electrolysis?",
   "body": "A fine probe and a tiny current treat each follicle so the hair stops growing back. Every hair colour, every skin tone, including grey and blonde.",
   "cta": "DM the word HAIR",
   "theme": "dark",
   "kind": "statement"
  },
  "meet-cleo-oakville": {
   "label": "Meet Cleo &#183; Oakville",
   "serif": "HI, I AM",
   "script": "Cleo.",
   "body": "Nurse practitioner, injector, and the only person you will see at the studio. One client at a time, every time.",
   "cta": "Say hi below",
   "theme": "light",
   "kind": "statement"
  },
  "facial-electrolysis-chin-upper-lip": {
   "label": "Facial Electrolysis &#183; Chin & Lip",
   "serif": "STOP",
   "script": "tweezing.",
   "body": "Facial electrolysis treats each chin and upper lip hair at the follicle, so it stops coming back. Fine, light and grey hairs included.",
   "cta": "DM the word HAIR",
   "theme": "dark",
   "kind": "statement"
  },
  "how-long-does-dermal-filler-last": {
   "label": "Dermal Fillers &#183; How Long They Last",
   "serif": "HOW LONG",
   "script": "does filler last?",
   "body": "Lips, which move all day, usually six to twelve months. Cheeks and chin often a year or more. Your body, the product and the area decide.",
   "cta": "Save this",
   "theme": "light",
   "kind": "statement"
  },
  "luxury-med-spa-oakville": {
   "label": "Luxury Med Spa &#183; Oakville",
   "serif": "LUXURY IS",
   "script": "time.",
   "body": "One client at a time, a private room, and a nurse practitioner who is never double booked. Nobody rushing you out the door.",
   "cta": "Come see the studio",
   "theme": "light",
   "kind": "statement"
  },
  "how-many-electrolysis-sessions": {
   "label": "Electrolysis &#183; Your Questions",
   "serif": "HOW MANY",
   "script": "sessions?",
   "body": "A course, not a single visit. Hair grows in cycles, so we treat follicles as they appear. Area, density and hormones decide how long.",
   "cta": "Ask me your area",
   "theme": "dark",
   "kind": "statement"
  },
  "electrolysis-aftercare": {
   "label": "Electrolysis &#183; Aftercare",
   "serif": "THE FIRST",
   "script": "48 hours.",
   "body": "Pink is normal. Clean hands, no makeup on the area, no heat or sun, no picking. Between sessions, trim, never tweeze.",
   "cta": "Save this",
   "theme": "dark",
   "kind": "statement"
  },
  "gift-certificates-oakville-med-spa": {
   "label": "Gift Certificates &#183; Now Available",
   "serif": "THE GIFT",
   "script": "of glow.",
   "body": "Any amount, for any treatment at the Oakville studio. Every one starts with a consult, so they get exactly what suits them.",
   "cta": "DM the word GIFT",
   "theme": "dark",
   "kind": "statement"
  },
  "why-cleo-says-no": {
   "label": "Honest Injecting &#183; Cleo",
   "serif": "WHY I",
   "script": "say no.",
   "body": "Not yet, not this, or not with me. Saying no is the part of the job that protects your face the most.",
   "cta": "Book an honest consult",
   "theme": "light",
   "kind": "statement"
  },
  "frown-lines-forehead-crows-feet": {
   "label": "Botox &#183; The Three Classic Areas",
   "serif": "THREE",
   "script": "areas.",
   "body": "Frown lines first for most. Forehead lines lightly, so brows still lift. Crow's feet softened, so your smile reaches your eyes.",
   "cta": "Which one is yours?",
   "theme": "dark",
   "kind": "statement"
  },
  "lip-filler-vs-lip-flip": {
   "label": "Lip Filler Or Lip Flip",
   "serif": "VOLUME",
   "script": "or show?",
   "body": "Filler adds volume and shape. A lip flip relaxes the muscle so a little more upper lip shows when you smile. Different problems, different tools.",
   "cta": "Tell me which",
   "theme": "light",
   "kind": "statement"
  },
  "black-friday-done-honestly": {
   "label": "Black Friday &#183; Done Honestly",
   "serif": "NEVER",
   "script": "on sale.",
   "body": "I do not discount injectables. Cheap units are how corners get cut. Gift certificates, though, are ready this week.",
   "cta": "DM the word GIFT",
   "theme": "dark",
   "kind": "statement"
  },
  "does-electrolysis-hurt": {
   "label": "Electrolysis FAQ",
   "serif": "DOES IT",
   "script": "hurt?",
   "body": "A quick warm sting per hair, most noticeable on the upper lip. Short, paced to you, and easier as the course goes on.",
   "cta": "Ask your question",
   "theme": "light",
   "kind": "statement"
  }
 }
};
